backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow

media_folder: 'wiki/media'
public_folder: '../media'

collections:
  - name: 'wiki' # Used in routes, e.g., /admin/collections/blog
    label: 'Wiki Entries'
    label_singular: 'Wiki Entry'
    description: 'Add to the collective lore of the realm'
    folder: 'wiki/entries' # The path to the folder where the documents are stored
    create: true
    delete: false
    extension: 'md'
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'string',
          default: 'Main',
        }
      - {
          label: 'Body',
          name: 'body',
          widget: 'markdown',
          default: 'Placeholder',
        }
    editor:
      preview: false
